export const dataList = [
  {
    id: 1,
    title: "My Portfolio",
    description: "My portfolio website, built with Next.js, Redux Toolkit for state management, Node.js and Express for the backend server, MongoDB for the database.✨🎉",
    image: "/screenshots/Portfolio1a.jpg",
    link: "https://my-portfolio-drstephen.vercel.app/",
    github: "https://github.com/dr-stephen-achugwo/My-Portfolio",
  },
  {
    id: 2,
    title: "Global Weather App",
    description: "A Weather application built with Next.js 😍 React.✨🎉",
    image: "/screenshots/Weather-App.png",
    link: "https://nextjs-weather-app-pearl.vercel.app/",
    github: "https://github.com/dr-stephen-achugwo/Nextjs-Weather-App",
  },
  {
    id: 3,
    title: "BgColorFlipper1",
    description: "This simple app is a Background Color Flipper. BgColorFlipper has a button. Click Simple and the color changes.✨🎉",
    image: "/screenshots/Simple.png",
    link: "https://art1app.com/pages/appz/BgCF-Simple.html",
    github: "https://github.com/dr-stephen/BgColorFlipper",
  },
  {
    id: 4,
    title: "BgColorFlipper2",
    description: "The next Background Color Flipper, BgColorFlipper2 has a button - Get New Hex. Click it to get another hex color.🎉✨",
    image: "/screenshots/Hex.png",
    link: "https://art1app.com/pages/appz/BgCF-Hex.html",
    github: "https://github.com/dr-stephen/BgColorFlipper",
  },
  {
    id: 5,
    title: "Tetris-Game",
    description: "An exciting game, built with JavaScript, css and html✨🎉",
    image: "/screenshots/Tetris.jpg",
    link: "https://art1app.com/mini-apps/Tetris-Game/index.html",
    github: "",
  },
  {
    id: 6,
    title: "Weather-App",
    description: "This is a weather web application using Html, Css, Javascript, Weathermap Api✨🎉",
    image: "/screenshots/weather-viewer-screenshot2.png",
    link: "https://art1app.com/pages/appz/Weather.html",
    github: "https://github.com/dr-stephen/Weather-App",
  },
  {
    id: 7,
    title: "BMI-Calculator",
    description: "BMI-Calculator✨🎉",
    image: "/screenshots/BMI-Calc1.png",
    link: "https://art1app.com/pages/appz/BMI-Calculator1.html",
    github: "https://github.com/dr-stephen/BMI-Calculator",
  },
  {
    id: 8,
    title: "BMI-Calculator2",
    description: "BMI-Calculator2✨🎉",
    image: "/screenshots/BMI-Calc2.png",
    link: "https://art1app.com/pages/appz/BMI-Calculator2.html",
    github: "https://github.com/dr-stephen/BMI-Calculator",
  },
  {
    id: 9,
    title: "Caesar-Cipher1",
    description: "Caesar-Cipher✨🎉",
    image: "/screenshots/Caesar-Cipher1.png",
    link: "https://art1app.com/pages/appz/Caesar-Cipher1.html",
    github: "https://github.com/dr-stephen/Caesar-Cipher",
  },
  {
    id: 10,
    title: "Caesar-Cipher2",
    description: "Caesar-Cipher2✨🎉",
    image: "/screenshots/Caesar-Cipher2.png",
    link: "https://art1app.com/pages/appz/Caesar-Cipher2.html",
    github: "https://github.com/dr-stephen/Caesar-Cipher",
  },
  {
    id: 11,
    title: "Caesar-Cipher3",
    description: "Caesar-Cipher3✨🎉",
    image: "/screenshots/Caesar-Cipher3.png",
    link: "https://art1app.com/pages/appz/Caesar-Cipher3.html",
    github: "https://github.com/dr-stephen/Caesar-Cipher",
  },
  {
    id: 12,
    title: "Background Color-Changer",
    description: "Background Color-Changer✨🎉",
    image: "/screenshots/BgColor-Changer.png",
    link: "https://art1app.com/mini-apps/BgColorChanger/index.html",
    github: "https://github.com/dr-stephen/BgColorChanger",
  },

  {
    id: 13,
    title: "Background Image Slider2",
    description: "Background Image Slider2✨🎉",
    image: "/screenshots/BgImageSlider2.jpg",
    link: "https://art1app.com/mini-apps/BgImageSlider2/index.html",
    github: "https://github.com/dr-stephen/BgImageSlider",
  },
  {
    id: 14,
    title: "Background Image Slider",
    description: "Background Image Slider✨🎉",
    image: "/screenshots/img-slider.jpg",
    link: "https://art1app.com/mini-apps/BgImageSlider/index.html",
    github: "https://github.com/dr-stephen/BgImageSlider",
  },
];
