import Loader from "react-loaders";
import Head from "next/head";
import dynamic from "next/dynamic";
import React, { useEffect, useState } from "react";
import { AnimatedLetters, ContactForm } from "../components";
import styles from "../styles/Contact.module.scss";


const Map = dynamic(() => import("../components/Map"), { ssr: false });

const Contact = () => {
  const [loading, setLoading] = useState(true);
  const [letterClass, setLetterClass] = useState("text__animate");
  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 1100);

    setTimeout(() => {
      setLetterClass("text__animate__hover");
    }, 6000);
  }, []);

  return (
    <>
      {loading ? (
        <Loader type="pacman" />
      ) : (
        <div className={styles.contact__wrapper}>
          <Head>
            <title>Contact Me</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/asicon.ico" />
          </Head>

          <span className={`${styles.tags} ${styles.top__tags}`}>
            &lt;body&gt;
          </span>
          <div className={styles.contact__inner}>
            <div className={styles.lhs}>
              <div className={styles.text__zone}>
                <h1>
                  <AnimatedLetters
                    letterClass={letterClass}
                    strArray={"Contact me".split("")}
                    idx={15}
                  />
                </h1>
                <p>
                  I&apos;m seeking for a job in Nextjs Reactjs or JavaScript.
                  I love being engaged in tech projects. If you have a 
                  request or question, don&apos;t hesitate to contact me.

                </p>
              </div>
              <ContactForm />
            </div>

            <div className={styles.rhs}>
              <Map />
            </div>
          </div>
          <span className={`${styles.tags} ${styles.bottom__tags}`}>
            &lt;/body&gt;
            <br />
            <span className={styles.bottom__tag__html}>&lt;/html&gt;</span>
          </span>
        </div>
      )}
    </>
  );
};

export default Contact;
