import Loader from "react-loaders";
import Head from "next/head";
import { useEffect, useState } from "react";
import { MainPage } from "../components";
import styles from "../styles/Home.module.scss";


export default function Home() {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 1500);
  }, []);
  
  return (
    <>
      {loading ? (
        <Loader type="pacman" />
      ) : (
        <div className={styles.container}>
          <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/asicon.ico" />
          </Head>

          <main className={styles.main}>
            <span className={`${styles.tags} ${styles.top__tags}`}>
              &lt;body&gt;
            </span>
            <MainPage />
            <span className={`${styles.tags} ${styles.bottom__tags}`}>
              &lt;/body&gt;                                            
              <br />
              <span className={styles.bottom__tag__html}>&lt;/html&gt;</span>
            </span>
          </main>
        </div>
      )}
    </>
  );
}

